-- MySQL Script generated by MySQL Workbench
-- Wed Apr 20 20:14:05 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema TicketProject
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TicketProject
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TicketProject` DEFAULT CHARACTER SET utf8 ;
USE `TicketProject` ;

-- -----------------------------------------------------
-- Table `TicketProject`.`Users_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TicketProject`.`Users_type` (
  `user_type_id` INT NOT NULL AUTO_INCREMENT,
  `user_type_type` VARCHAR(45) NULL,
  PRIMARY KEY (`user_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TicketProject`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TicketProject`.`Users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NULL,
  `user_lastname` VARCHAR(45) NULL,
  `user_username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `user_user_type` INT NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_Users_Users_type1_idx` (`user_user_type` ASC),
  CONSTRAINT `fk_Users_Users_type1`
    FOREIGN KEY (`user_user_type`)
    REFERENCES `TicketProject`.`Users_type` (`user_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TicketProject`.`Status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TicketProject`.`Status` (
  `status_id` INT NOT NULL AUTO_INCREMENT,
  `status_type` VARCHAR(45) NULL,
  PRIMARY KEY (`status_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TicketProject`.`Messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TicketProject`.`Messages` (
  `message_id` INT NOT NULL AUTO_INCREMENT,
  `message_date` TIMESTAMP NULL,
  `message_text` TEXT NULL,
  `message_user_id` INT NOT NULL,
  PRIMARY KEY (`message_id`),
  INDEX `fk_Messages_Users1_idx` (`message_user_id` ASC),
  CONSTRAINT `fk_Messages_Users1`
    FOREIGN KEY (`message_user_id`)
    REFERENCES `TicketProject`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TicketProject`.`Tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TicketProject`.`Tickets` (
  `ticket_id` INT NOT NULL AUTO_INCREMENT,
  `ticket_titre` VARCHAR(45) NULL,
  `ticket_user_id` INT NULL,
  `ticket_admin_id` INT NULL,
  `ticket_status_id` INT NOT NULL,
  `ticket_message_id` INT NOT NULL,
  PRIMARY KEY (`ticket_id`),
  INDEX `fk_Tickets_Users1_idx` (`ticket_user_id` ASC),
  INDEX `fk_Tickets_Users2_idx` (`ticket_admin_id` ASC),
  INDEX `fk_Tickets_Status1_idx` (`ticket_status_id` ASC),
  INDEX `fk_Tickets_Messages1_idx` (`ticket_message_id` ASC),
  CONSTRAINT `fk_Tickets_Users1`
    FOREIGN KEY (`ticket_user_id`)
    REFERENCES `TicketProject`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tickets_Users2`
    FOREIGN KEY (`ticket_admin_id`)
    REFERENCES `TicketProject`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tickets_Status1`
    FOREIGN KEY (`ticket_status_id`)
    REFERENCES `TicketProject`.`Status` (`status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tickets_Messages1`
    FOREIGN KEY (`ticket_message_id`)
    REFERENCES `TicketProject`.`Messages` (`message_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
